### ISSUE TITLE
# Add Domain Name to the Github-page settings

### ISSUE THREAD

**Issue by tris460** [ElectronicCats/arduino-day-aguascalientes2021#9]

**Comment by wolftrax5** [comment]
This config is all ready done with the DNS of [Hostinger](https://www.hostinger.mx/) & [Managing a custom domain for your GitHub Pages site DOC](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)
